# Generated by Django 4.2.4 on 2023-11-11 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_license_number', models.CharField(max_length=20)),
                ('bus_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('model_serial_number', models.CharField(max_length=200)),
                ('max_passenger', models.IntegerField()),
                ('engine', models.CharField(max_length=200)),
                ('low_floow_TF', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=200)),
                ('stop_time', models.IntegerField()),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusStopping.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField()),
                ('bus_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BusStopping.busstation')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusStopping.route')),
            ],
            options={
                'ordering': ['route', 'order_num'],
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_count', models.IntegerField()),
                ('bus_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusStopping.busstation')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusStopping.dispatch')),
            ],
        ),
        migrations.AddField(
            model_name='dispatch',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusStopping.route'),
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusStopping.busmodel'),
        ),
    ]
