# Generated by Django 4.1.7 on 2023-11-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusStopping', '0002_alter_dispatch_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatch',
            options={'ordering': ['route', 'bus']},
        ),
        migrations.AddField(
            model_name='stationroute',
            name='move_time',
            field=models.IntegerField(null=True),
        ),
    ]
