# Generated by Django 4.2.7 on 2023-11-16 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusStopping', '0003_alter_dispatch_options_stationroute_move_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationroute',
            name='bus_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_route', to='BusStopping.busstation'),
        ),
        migrations.AlterField(
            model_name='stationroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_station', to='BusStopping.route'),
        ),
    ]
